# This is a basic workflow to help you get started with Actions

name: Push from Tag

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Modify Readme
      run: echo $(date) >> README.md


    - name: Commit Changelog
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
          commit_message: Update README
          file_pattern: README.md
